# Generated by Django 6.0.7 on 2026-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_booking_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='service_price_gt_zero'),
        ),
    ]
