# Generated by Django 6.0.7 on 2026-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_service_price_gt_zero'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('service', 'booking_date'), name='unique_active_booking_slot'),
        ),
    ]
